### ISSUE TITLE
Annotation test: Vatic+AWS Sagemaker

### ISSUE THREAD

**Issue by TaniaPash** [teamklap/vatic.js#2]
## Steps

-  start a helmet and horses annotation task using vatic + sagemaker and https://docs.google.com/spreadsheets/d/17Eaz6xNYXpQAwTgq-57hFiyvzggVuKMCcCtrfGunx3Q/edit#gid=1815652519
- ask smita to test it
- Try to use public workers on the same task
- Compare fscore of both

**Comment by TaniaPash** [comment]
Please test new bounding coxes annotation workflow using vatic + AWS Sagemaker. 

### Steps

1. check your mail with a link to the annotation room and a first task.
2. change the password (you'll be asked to do it once you click on a link in the mail)
3. click on a Job name in a list
4. click on `Start working`
5. annotate first 20 frames
6. click on Submit btn at the top of a screen (it looks like a text now)

**Comment by smitajha** [comment]
1. Bounding box is not being created where user draw "+" to create bbox. Bounding box is being created at some other place in that frame.Later user has to search the created bbox in the whole frame.
2. If a small bbox is  surrounded by a bigger bbox, then annonator cannot edit the size of smaller bbox, even if cursor is taken on the smaller bounding box.
3. There is no instruction given on  editing the size of bounding box. 
4. Annotation is not saving automatically if

**Comment by TaniaPash** [comment]
moved to https://github.com/teamklap/sls-node-vatic/issues/1
